name: buildAndDeploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.1

    - name: buildAndDeploy
      env:
        VITE_YOUTUBE_API: ${{ secrets.VITE_YOUTUBE_API }}
        VITE_GOOGLE_CLIENT_ID : ${{ secrets.VITE_GOOGLE_CLIENT_ID  }}
        VITE_BACK_URL : ${{ secrets.VITE_BACK_URL  }}
      run: |
        yarn install
        yarn build
        
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.